version: '3'
services:
  web:
    image: "gururajmujumdar/spefinal"
    build: .
    command: "node app.js"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"